# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lhoodcpp <- function(eta, beta, doc_ct, mu, siginv) {
    .Call(`_stm_lhoodcpp`, eta, beta, doc_ct, mu, siginv)
}

gradcpp <- function(eta, beta, doc_cts, mu, siginv) {
    .Call(`_stm_gradcpp`, eta, beta, doc_cts, mu, siginv)
}

hpbcpp <- function(eta, beta, doc_ct, mu, siginv, sigmaentropy) {
    .Call(`_stm_hpbcpp`, eta, beta, doc_ct, mu, siginv, sigmaentropy)
}

n_beta_sumcpp <- function(sumc_, aw, input_) {
    invisible(.Call(`_stm_n_beta_sumcpp`, sumc_, aw, input_))
}

n_sigma_sumcpp <- function(sumc_, input_) {
    invisible(.Call(`_stm_n_sigma_sumcpp`, sumc_, input_))
}

